tools:
  Nmap:
    name: "nmap"
    exePath: "H:\tools\Penetration\tools\01 scan\Nmap\nmap.exe"
    command: "{{exePath}} {{target}}"
    description: "扫描工具"
    defaultArgs: ""

  Fscan:
    name: "fscan"
    exePath: "H:\tools\Penetration\tools\01 scan\fscan\fscan.exe"
    command: "{{exePath}} -h {{target}}"
    description: "内网扫描工具"
    defaultArgs: ""

  Dirsearch:
    name: "Dirsearch"
    exePath: "H:\tools\Penetration\tools\01 scan\dirsearch\dirsearch.py"
    command: "python3.9 {{exePath}} -u {{target}}"
    description: "目录扫描工具"
    defaultArgs: ""

  nuclei:
    name: "nuclei"
    exePath: "H:\tools\Penetration\tools\00 Assemble tool\nuclei\nuclei.exe"
    command: "{{exePath}} -target {{target}}"

