tools:
  Nmap:
    name: "nmap.exe"
    exePath: "C:\\your\\nmap\\dir\\"
    command: "./{{name}} {{target}}"
    description: "扫描工具"
    defaultArgs: ""

  Fscan:
    name: "fscan.exe"
    exePath: "C:\\your\\fscan\\dir\\"
    command: "./{{name}} -h {{target}}"
    description: "内网扫描工具"
    defaultArgs: ""

  dirsearch:
    name: "dirsearch.py"
    exePath: "C:\\your\\dirsearch\\dir\\"
    command: "python3.9 {{name}} -u {{target}}"
    description: "目录扫描工具"
    defaultArgs: ""